_target_: instant_avatar.datasets.custom.CustomDataModule
name: neuman
subject: lab
gender: neutral
opt:
  dataroot: ./data/custom/${dataset.subject}/
  subject: ${dataset.subject}
  train:
    num_workers: 8
    batch_size: 1
    start: 0
    end: 80
    skip: 1
    downscale: 1
    sampler: ${sampler}
    fitting: ${model.opt.optimize_SMPL.enable}
    refine: ${model.opt.optimize_SMPL.is_refine}
  val:
    num_workers: 4
    batch_size: 1
    start: 52
    end: 53
    skip: 4
    downscale: 1
  test:
    num_workers: 4
    batch_size: 1
    start: 81
    end: 104
    skip: 1
    downscale: 1
